apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: amazon-prime-deploy
  name: amazon-prime-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amazon-prime-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: amazon-prime-deploy
    spec:
      containers:
      - image: pradyumnam/amazon-prime-clone:v1
        name: amazon-prime-clone
        ports:
        - containerPort: 80
        resources: {}
status: {}