apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: amazon-prime-deploy
  name: amazon-prime-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: amazon-prime-deploy
  type: NodePort
status:
  loadBalancer: {}